spring.application.name=securitas-cash

# BD for production
spring.datasource.url=jdbc:postgresql://localhost:5432/securitascash2
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# server
server.port=8080

#logging
logging.level.org.springframework.web=DEBUG


# Define o tamanho padrão de página para 15 para toda a aplicação
spring.data.web.pageable.default-page-size=8

# [RECOMENDADO] Define um tamanho máximo de página para evitar abuso da API
# Se o usuário pedir ?size=5000, ele receberá apenas 100.
spring.data.web.pageable.max-page-size=15

# Opcional: faz a contagem de páginas começar em 1 em vez de 0 para as requisições
# Ex: ?page=1 será a primeira página. O Spring converte internamente para 0.
# spring.data.web.pageable.one-indexed-parameters=true